import type { TagSeed } from "./types";

export const tagSeeds = [
  { name: "Python", slug: "python" },
  { name: "PyTorch", slug: "pytorch" },
  { name: "Vision Transformer", slug: "vision-transformer" },
  { name: "timm", slug: "timm" },
  { name: "Volatility 3", slug: "volatility-3" },
  { name: "Memory Forensics", slug: "memory-forensics" },
  { name: "Malware Detection", slug: "malware-detection" },
  { name: "Computer Vision", slug: "computer-vision" },
  { name: "Explainable AI", slug: "explainable-ai" },
  { name: "Multiprocessing", slug: "multiprocessing" },
  { name: "scikit-learn", slug: "scikit-learn" },
  { name: "DFIR", slug: "dfir" },
  { name: "CLI", slug: "cli" },
  { name: "pandas", slug: "pandas" },
  { name: "Rich", slug: "rich" },
  { name: "Concurrency", slug: "concurrency" },
  { name: "Caching", slug: "caching" },
  { name: "JSON", slug: "json" },
  { name: "JSONL", slug: "jsonl" },
  { name: "CSV", slug: "csv" },
  { name: "SMDA", slug: "smda" },
  { name: "Control-Flow Graphs", slug: "control-flow-graphs" },
  { name: "Call Graphs", slug: "call-graphs" },
  { name: "NetworkX", slug: "networkx" },
  { name: "PyTorch Geometric", slug: "pytorch-geometric" },
  { name: "GraphSAGE", slug: "graphsage" },
  { name: "DiffPool", slug: "diffpool" },
  { name: "Transformers", slug: "transformers" },
  { name: "Malware Classification", slug: "malware-classification" },
] as const satisfies readonly TagSeed[];
